---
- hosts: all
  become: true
  tasks:
  - name: Install Docker
    yum: name=docker state=present
  - name: Start Docker Service
    command: sudo systemctl start docker
  - name: Deploy your application and run as a container
    command: docker run -itd -p 8084:8081 belosheabhijeet/insure-me-app:2.0
